version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "chopper"
      # Allow both direct and indirect updates for all packages
      - dependency-type: "direct"
    # Specify labels pull requests
    labels:
      - "dependencies"
    # Add reviewers
    reviewers:
      - "jayjah"