name: calendarific_dart
description: |
  A dart package to retrieve data from calendarific API.
  Get holidays from specific country, year and moreover retrieve languages and countries 
  from their API.
version: 1.0.2
repository: https://github.com/jayjah/calendarific_dart
homepage: https://markus.jayjah.de
issue_tracker: https://github.com/jayjah/calendarific_dart/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  chopper: ^4.0.5

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.0
  chopper_generator: any
  build_runner: any
  dart_code_metrics: ^4.14.0